language: php
php:
  - '7.1'
git:
  submodules: true
cache:
  directories: node_modules
services:
  - mysql  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver
      - php5-fpm
      - php5-mysql
      - nginx
hosts:
  - bookings.test.com
env:
  global:
    - DB_NAME="test_engine"
before_install:
  - mysql -e "create database IF NOT EXISTS $DB_NAME;"
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -u root -e "GRANT ALL ON $DB_NAME.* TO 'root'@'localhost';"
  - mysql -u root --database=$DB_NAME < migrate.sql
  - mysql -u root --database=$DB_NAME < seed.sql
before_script:
  - nvm install v10
  - whereis google-chrome-stable
  - whereis chromedriver
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn install
  - yarn test
  - ls
  - sudo service php5-fpm restart
  - sudo service nginx restart
scripts:
  - ls